site_name: PremièreFable
site_description: Traduction française du JDR américain FirstFable
site_author: Matthew McFarland, Olivier Rey
copyright: Site sous licence Creative Common v3
google_analytics: ['UA-110156293-1', 'orey.github.io']
theme: windmill
site_dir: site
nav:
- 'Home': 'index.md'
- 'PremièreFable, le jeu':
    - 'Qu''est-ce que le jeu de rôles ?': 'pages/01-Le-jeu-de-roles-en-deux-mots.md'
    - 'Introduction': 'pages/02-Introduction.md'
    - 'Création des personnages': 'pages/03-Creation-des-personnages.md'
    - 'Règles du jeu': 'pages/04-Regles-du-jeu.md'
    - 'Gérer le déroulement du jeu': 'pages/05-Diriger-le-jeu.md'
    - 'Synthèse du jeu': 'pages/97-Synthese-du-jeu.md'
    - 'Conclusion': 'pages/07-Conclusion.md'
    - 'Contenu de la feuille de personnage': 'pages/09-fdp.md'
- 'Scénarios':
    - 'La chasse au Dahu sauvage': 'pages/06-La-chasse-au-Dahu-sauvage.md'
- 'A propos':
    - 'License': 'pages/LICENCE.md'
    - 'PDF originaux en anglais': 'pages/08-FirstFable.md'
    - 'Notes du traducteur': 'pages/98-Notes-du-traducteur.md'
    - 'To do list': 'pages/99-To-Do-list.md'
extra:
    logo: images/logo-guide.png
    version: v0.9
